#!/usr/bin/env node
// Generate per-vendor agent files (rules, slash commands, skills) from the canonical
// playbooks in playbooks/. Single source of truth: playbooks/*.md. Generated files are
// gitignored and rebuilt on demand — edit the playbook, never the generated file.
//
// Usage:
//   node scripts/gen-agents.mjs                       # all registered vendors
//   node scripts/gen-agents.mjs --vendors="cursor"    # a subset (space/comma separated)
//   node scripts/gen-agents.mjs --clean               # remove what it would generate
//   node scripts/gen-agents.mjs --clean --vendors="cursor"
//
// Dependency-free (Node built-ins only).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PLAYBOOKS_DIR = path.join(ROOT, "playbooks");

// --- Renderers ---------------------------------------------------------------

const banner = (file) =>
  `<!-- GENERATED by \`make agents\` — do not edit. Edit playbooks/${file} instead. -->`;

const pointer = (ctx) =>
  `Read and follow the playbook at \`playbooks/${ctx.file}\` (from the repo root) and carry out its instructions.`;

function yamlScalar(v) {
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  const s = String(v);
  // Quote anything that could confuse a YAML parser.
  if (/[:#\[\]{}&*!|>'"%@`,]/.test(s)) return JSON.stringify(s);
  return s;
}

function frontmatter(obj) {
  const lines = Object.entries(obj).map(([k, v]) => `${k}: ${yamlScalar(v)}`);
  return `---\n${lines.join("\n")}\n---\n`;
}

function renderCursorRule(ctx) {
  return (
    frontmatter({ description: ctx.description, alwaysApply: true }) +
    `\n${banner(ctx.file)}\n\n${ctx.body.trim()}\n`
  );
}

function renderClaudeRule(ctx) {
  return (
    `${banner(ctx.file)}\n\n# Alufim — agent guide\n\n` +
    "See `AGENTS.md` for full project guidance and the knowledge base entry point.\n\n" +
    `${ctx.body.trim()}\n`
  );
}

function renderCursorCommand(ctx) {
  return `${banner(ctx.file)}\n\n# ${ctx.name}\n\n${pointer(ctx)}\n`;
}

function renderClaudeCommand(ctx) {
  return (
    frontmatter({ description: ctx.description }) +
    `\n${banner(ctx.file)}\n\n${pointer(ctx)}\n`
  );
}

function renderSkill(ctx) {
  return (
    frontmatter({ name: ctx.name, description: ctx.description }) +
    `\n${banner(ctx.file)}\n\n${pointer(ctx)}\n`
  );
}

// --- Registry: vendor x kind -> { path, render } -----------------------------
// Adding a vendor (or a kind) is a single self-contained entry here.

const REGISTRY = {
  cursor: {
    rule: { path: (n) => `.cursor/rules/${n}.mdc`, render: renderCursorRule },
    command: { path: (n) => `.cursor/commands/${n}.md`, render: renderCursorCommand },
    skill: { path: (n) => `.cursor/skills/${n}/SKILL.md`, render: renderSkill },
  },
  claude: {
    rule: { path: () => `CLAUDE.md`, render: renderClaudeRule },
    command: { path: (n) => `.claude/commands/${n}.md`, render: renderClaudeCommand },
    skill: { path: (n) => `.claude/skills/${n}/SKILL.md`, render: renderSkill },
  },
  // future: codex, gemini, ... just add an entry here.
};

const ALL_VENDORS = Object.keys(REGISTRY);

// --- Parsing -----------------------------------------------------------------

function parseFrontmatter(raw) {
  const lines = raw.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") return { data: {}, body: raw };
  const fmLines = [];
  let i = 1;
  for (; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      i++;
      break;
    }
    fmLines.push(lines[i]);
  }
  const body = lines.slice(i).join("\n").replace(/^\n+/, "");
  const data = {};
  for (const line of fmLines) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!m) continue;
    let val = m[2].trim();
    if (val.startsWith("[") && val.endsWith("]")) {
      val = val
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, "");
    }
    data[m[1]] = val;
  }
  return { data, body };
}

const asArray = (v) => (Array.isArray(v) ? v : v == null ? [] : [v]);

// --- CLI ---------------------------------------------------------------------

function parseVendorsArg() {
  const arg = process.argv.find((a) => a.startsWith("--vendors="));
  const raw = arg ? arg.slice("--vendors=".length).replace(/^["']|["']$/g, "").trim() : "";
  if (!raw) return ALL_VENDORS;
  const requested = raw.split(/[\s,]+/).filter(Boolean);
  const unknown = requested.filter((v) => !REGISTRY[v]);
  if (unknown.length) {
    fail(`Unknown vendor(s): ${unknown.join(", ")}. Supported: ${ALL_VENDORS.join(", ")}.`);
  }
  return requested;
}

function fail(msg) {
  console.error(`gen-agents: ${msg}`);
  process.exit(1);
}

// Remove now-empty ancestor directories of a deleted file, stopping at ROOT.
function pruneEmptyDirs(fileAbs) {
  let dir = path.dirname(fileAbs);
  while (dir.startsWith(ROOT) && dir !== ROOT) {
    try {
      if (fs.readdirSync(dir).length > 0) break;
      fs.rmdirSync(dir);
    } catch {
      break;
    }
    dir = path.dirname(dir);
  }
}

// Resolve the set of files gen-agents owns for the selected vendors. Both generating
// and cleaning share this, so `clean` removes exactly what would be generated.
function resolveTargets(selectedVendors) {
  if (!fs.existsSync(PLAYBOOKS_DIR)) fail(`No playbooks/ directory at ${PLAYBOOKS_DIR}.`);
  const files = fs.readdirSync(PLAYBOOKS_DIR).filter((f) => f.endsWith(".md"));
  if (!files.length) fail("No playbooks found in playbooks/.");

  const ownedBy = new Map(); // absolute path -> source playbook file
  const targets = [];

  for (const file of files.sort()) {
    const raw = fs.readFileSync(path.join(PLAYBOOKS_DIR, file), "utf8");
    const { data, body } = parseFrontmatter(raw);

    const name = data.name;
    const description = data.description || "";
    if (!name) fail(`playbooks/${file}: missing 'name' in frontmatter.`);
    const kinds = asArray(data.kind);
    if (!kinds.length) fail(`playbooks/${file}: missing 'kind' in frontmatter.`);

    // A playbook may restrict its vendors; otherwise it targets all selected ones.
    const playbookVendors = data.vendors ? asArray(data.vendors) : selectedVendors;
    const vendors = selectedVendors.filter((v) => playbookVendors.includes(v));

    const command = data.command || name;

    for (const vendor of vendors) {
      for (const kind of kinds) {
        const cell = REGISTRY[vendor]?.[kind];
        if (!cell) {
          fail(
            `playbooks/${file}: vendor '${vendor}' does not support kind '${kind}'. ` +
              `Supported kinds for ${vendor}: ${Object.keys(REGISTRY[vendor]).join(", ")}.`
          );
        }
        const idName = kind === "command" ? command : name;
        const rel = cell.path(idName);
        const abs = path.join(ROOT, rel);

        if (ownedBy.has(abs)) {
          fail(
            `Output collision on '${rel}': both playbooks/${ownedBy.get(abs)} and ` +
              `playbooks/${file} target it (e.g. two kind:rule playbooks map to a single CLAUDE.md).`
          );
        }
        ownedBy.set(abs, file);
        targets.push({ rel, abs, render: () => cell.render({ name, description, command, body, file }) });
      }
    }
  }

  return targets;
}

// --- Main --------------------------------------------------------------------

function main() {
  const selectedVendors = parseVendorsArg();
  const clean = process.argv.includes("--clean");
  const targets = resolveTargets(selectedVendors);
  const touched = [];

  for (const t of targets) {
    if (clean) {
      if (!fs.existsSync(t.abs)) continue;
      fs.rmSync(t.abs);
      pruneEmptyDirs(t.abs);
      touched.push(t.rel);
    } else {
      fs.mkdirSync(path.dirname(t.abs), { recursive: true });
      fs.writeFileSync(t.abs, t.render());
      touched.push(t.rel);
    }
  }

  const verb = clean ? "removed" : "wrote";
  console.log(
    `gen-agents: ${verb} ${touched.length} file(s) for vendor(s) [${selectedVendors.join(", ")}]:`
  );
  for (const o of touched.sort()) console.log(`  ${o}`);
}

main();
